"use client";

import { useState } from "react";
import { ArrowRight, BriefcaseBusiness, ChevronDown, Code2, FolderGit2, Link2, Sparkles, Star, Trophy } from "lucide-react";

const roles = ["Frontend Developer", "AI/ML Engineer", "Full-Stack Developer"];
const experienceLevels = [{ label: "Fresher", icon: Trophy }, { label: "1–3 yrs", icon: BriefcaseBusiness }, { label: "Senior", icon: Star }];

export default function Getform() {
  const [repository, setRepository] = useState(""); const [role, setRole] = useState(roles[0]); const [experience, setExperience] = useState("Fresher"); const [open, setOpen] = useState(false); const [submitted, setSubmitted] = useState(false);
  return <div className="relative flex min-h-screen justify-center overflow-hidden bg-[#fafbff] px-4 py-10 text-[#111936]"><div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_50%_39%,rgba(104,82,255,.12),transparent_22rem),radial-gradient(circle_at_10%_94%,rgba(119,93,255,.12),transparent_18rem)]" /><main className="relative w-full max-w-[680px]">
    <header className="mb-7 text-center"><p className="mb-2 text-xs font-extrabold tracking-[.13em] text-[#5146f2]">SKILL-FIRST EVALUATION</p><h1 className="text-4xl font-extrabold leading-none tracking-[-.055em] sm:text-5xl">Show Us What You&apos;ve Built</h1><p className="mt-3 text-[15px] text-[#68708a] sm:text-[17px]">Paste your GitHub repo or portfolio link — no resume needed.</p></header>
    <form className="rounded-2xl border border-[#e9eaf2] bg-white/90 p-5 shadow-[0_15px_34px_rgba(38,45,80,.12)] sm:p-6" onSubmit={(e) => { e.preventDefault(); setSubmitted(true); }}>
      <label className="mb-2 flex items-center justify-between text-sm font-bold text-[#1d2642]" htmlFor="repository">GitHub Repository or Portfolio Link <FolderGit2 size={17} /></label><div className="flex h-12 items-center gap-3 rounded-lg border border-[#dfe2ec] bg-white px-3 text-[#7e879e]"><Link2 size={18} /><input className="w-full min-w-0 border-0 bg-transparent text-sm text-[#1d2642] outline-none placeholder:text-[#a0a7b8]" id="repository" value={repository} onChange={(e) => setRepository(e.target.value)} placeholder="https://github.com/username/project" type="url" required /></div>
      <div className="relative mt-4"><span className="mb-2 flex text-sm font-bold text-[#1d2642]">Target Role</span><button className="flex h-12 w-full items-center gap-3 rounded-lg border border-[#dfe2ec] bg-white px-3 text-left text-sm text-[#7e879e]" type="button" onClick={() => setOpen(!open)}><BriefcaseBusiness size={18} /><span className="flex-1">{role}</span><ChevronDown size={18} className={open ? "rotate-180 transition-transform" : "transition-transform"} /></button>{open && <div className="absolute z-10 w-full overflow-hidden rounded-lg border border-[#e3e5ef] bg-white shadow-lg">{roles.map((item) => <button key={item} type="button" className={`flex w-full items-center gap-3 px-3 py-3 text-left text-sm hover:bg-[#f2f1ff] hover:text-[#5146f2] ${item === role ? "bg-[#f2f1ff] text-[#5146f2]" : "text-[#303852]"}`} onClick={() => { setRole(item); setOpen(false); }}><Code2 size={16} />{item}</button>)}</div>}</div>
      <fieldset className="my-5 border-0 p-0"><legend className="mb-2 text-sm font-bold text-[#1d2642]">Experience Level</legend><div className="grid grid-cols-3 gap-2">{experienceLevels.map(({ label, icon: Icon }) => <button key={label} type="button" onClick={() => setExperience(label)} className={`flex h-11 items-center justify-center gap-1.5 rounded-md border text-xs sm:text-sm ${experience === label ? "border-[#5548f4] bg-gradient-to-r from-[#4238e9] to-[#6658ff] text-white shadow-md" : "border-[#dfe2ec] bg-white text-[#4f5871]"}`}><Icon size={16} />{label}</button>)}</div></fieldset>
      <button className="flex h-11 w-full items-center justify-center gap-2 rounded-md bg-gradient-to-r from-[#4038e8] to-[#6657ff] text-sm font-bold text-white shadow-md hover:brightness-105" type="submit">Analyze My Work <ArrowRight size={19} /></button>{submitted && <p className="mt-3 text-center text-sm font-semibold text-[#168254]">Your work is ready to be analyzed.</p>}
    </form><div className="mt-7 grid gap-4 sm:grid-cols-3"><Benefit icon={FolderGit2} title="GitHub API" text="Securely fetches your code and metadata" /><Benefit icon={Sparkles} title="AI Code Review" text="Analyzes code quality, structure, and best practices" /><Benefit icon={Code2} title="Instant Report" text="Get detailed insights and suggestions" /></div>
  </main></div>;
}
function Benefit({ icon: Icon, title, text }) { return <article className="flex gap-3 sm:border-r sm:border-[#e3e5ef] sm:px-4 sm:last:border-0"><span className="grid size-11 shrink-0 place-items-center rounded-full bg-[#eeedff] text-[#6254f8]"><Icon size={21} /></span><div><h2 className="mt-0.5 text-xs font-bold">{title}</h2><p className="mt-1 text-[11px] leading-snug text-[#737b90]">{text}</p></div></article>; }
